### ISSUE TITLE
xombrero-gtk2-git AUR repository

### ISSUE THREAD

**Issue by epitron** [tukoz/PKGBUILDs#1]
This is nice! I like the GTK2 widgets! Why don't you add this to AUR?

(I can do it if you don't feel like it...)

**Comment by tukoz** [comment]
Hey, thank you for maintaining the xombrero-git pkgbuild.

Yeah xombrero gtk2 in whitelist makes even the slowest netbook from 2009, errr, a super responsive [kiss](https://simple.wikipedia.org/wiki/KISS_%28principle%29) baby :)

I'll add it to AUR this week.

**Comment by tukoz** [comment]
Almost ready to go. Asked [for review](https://bbs.archlinux.org/viewtopic.php?id=212904) and possible advice on how to not mess things up between github and AUR.git

**Comment by epitron** [comment]
Awesome! Can't wait to use it.

Judging by the forum responses, I should clean up my build file once yours is done. :)

**Comment by tukoz** [comment]
@epitron my forked PKGBUILD's failing on the LICENCE installation; may I ask how you manage to get that installed?

EDIT: OK since xombrero dev did not see fit to include it in its source you made it yourself. Got it.

**Comment by tukoz** [comment]
Uploaded to AUR.
#https://github.com/tukoz/pkgbuilds-1/commit/368920115f353dc8facdc7d7baf0de2535f6ea50
